-- ============================================================
-- INFINITE ZEN - SISTEMA DE IDIOMAS (MULTI-LANG)
-- ============================================================

local Language = {}

Language.current = "en"
Language.listeners = {}

Language.translations = {
    -- ═══════════════════════════════════════════════════════════
    -- PORTUGUÊS (BR)
    -- ═══════════════════════════════════════════════════════════
    ["pt-br"] = {
        flag = "BR", displayName = "Portugues (BR)", shortCode = "BR",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Edition", language_label = "Idioma",
        tab_combat = "Combat", tab_weapon = "Armas", tab_movement = "Movimento",
        tab_visuals = "Visual", tab_settings = "Config", tab_credits = "Creditos",
        silent_headshot = "Silent Headshot", silent_fov = "FOV do Silent",
        aimbot = "Aimbot", aimbot_fov = "FOV do Aimbot", aimbot_smooth = "Suavidade",
        aimbot_wallcheck = "Aimbot: Verificar Parede", triggerbot = "Triggerbot",
        triggerbot_delay = "Delay do Triggerbot", head_expander = "Head Expander",
        head_size = "Tamanho da Cabeca", backstab = "Backstab",
        no_recoil = "Sem Recuo", no_spread = "Sem Dispersao", rapid_fire = "Tiro Rapido",
        fast_reload = "Recarga Rapida", insta_reload = "Recarga Instantanea",
        infinite_ammo = "Municao Infinita", auto_shoot = "Tiro Automatico",
        auto_shoot_fov = "FOV do Tiro Auto",
        speed = "Velocidade", speed_value = "Valor da Velocidade", air_jump = "Pulo no Ar",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Distancia Maxima", weapon_esp = "ESP de Arma",
        armor_esp = "ESP de Armadura", grenade_esp = "ESP de Granada",
        damage_indicator = "Indicador de Dano",
        low_graphics = "Graficos Baixos", no_shadows = "Sem Sombras",
        no_fog = "Sem Nevoeiro", no_particles = "Sem Particulas",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-Votekick",
        interface_label = "Interface", save_config = "Salvar Config", load_config = "Carregar Config",
        info_label = "Info", key_minimize = "K = Minimizar UI",
        keybind_help1 = "Cada feature tem sua keybind", keybind_help2 = "Clique pra gravar",
        unload_script = "Descarregar Script", version_text = "Infinite Zen v1.0",
        on = "Ligado", off = "Desligado", key = "tecla",
        config_saved = "Config salva", config_loaded = "Config carregada",
        config_error_save = "Falha ao salvar", config_error_load = "Nenhum config",
        config_error_corrupt = "Arquivo corrompido", keybind_locked = "Keybind Bloqueada",
        keybind_locked_desc = "K reservada para UI", keybind_inuse = "Em Uso",
        keybind_inuse_desc = " ja usada por: ", backstab_target = "Backstab: ",
        no_enemy = "Nenhum inimigo", config_title = "Config", error_title = "Erro",
        load_title = "Carregar", unsupported_title = "Jogo Nao Suportado",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- ENGLISH
    -- ═══════════════════════════════════════════════════════════
    ["en"] = {
        flag = "US", displayName = "English (US)", shortCode = "US",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Edition", language_label = "Language",
        tab_combat = "Combat", tab_weapon = "Weapon", tab_movement = "Movement",
        tab_visuals = "Visuals", tab_settings = "Settings", tab_credits = "Credits",
        silent_headshot = "Silent Headshot", silent_fov = "Silent FOV",
        aimbot = "Aimbot", aimbot_fov = "Aimbot FOV", aimbot_smooth = "Smoothness",
        aimbot_wallcheck = "Aimbot Wall Check", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Delay", head_expander = "Head Expander",
        head_size = "Head Size", backstab = "Backstab",
        no_recoil = "No-Recoil", no_spread = "No Spread", rapid_fire = "Rapid Fire",
        fast_reload = "Fast Reload", insta_reload = "Insta-Reload",
        infinite_ammo = "Infinite Ammo", auto_shoot = "Auto Shoot",
        auto_shoot_fov = "Auto Shoot FOV",
        speed = "Speed", speed_value = "Speed Value", air_jump = "Air Jump",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Max Distance", weapon_esp = "Weapon ESP",
        armor_esp = "Armor ESP", grenade_esp = "Grenade ESP",
        damage_indicator = "Damage Indicator",
        low_graphics = "Low Graphics", no_shadows = "No Shadows",
        no_fog = "No Fog", no_particles = "No Particles",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Interface", save_config = "Save Config", load_config = "Load Config",
        info_label = "Info", key_minimize = "K = Minimize UI",
        keybind_help1 = "Each feature has its own keybind", keybind_help2 = "Click to record",
        unload_script = "Unload Script", version_text = "Infinite Zen v1.0",
        on = "ON", off = "OFF", key = "key",
        config_saved = "Config saved", config_loaded = "Config loaded",
        config_error_save = "Failed to save", config_error_load = "No config",
        config_error_corrupt = "Corrupted file", keybind_locked = "Keybind Blocked",
        keybind_locked_desc = "K reserved for UI", keybind_inuse = "In Use",
        keybind_inuse_desc = " already used by: ", backstab_target = "Backstab: ",
        no_enemy = "No enemy found", config_title = "Config", error_title = "Error",
        load_title = "Load", unsupported_title = "Unsupported Game",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- ESPAÑOL
    -- ═══════════════════════════════════════════════════════════
    ["es"] = {
        flag = "ES", displayName = "Espanol (ES)", shortCode = "ES",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Edition", language_label = "Idioma",
        tab_combat = "Combate", tab_weapon = "Armas", tab_movement = "Movimiento",
        tab_visuals = "Visuales", tab_settings = "Ajustes", tab_credits = "Creditos",
        silent_headshot = "Headshot Silencioso", silent_fov = "FOV Silencioso",
        aimbot = "Aimbot", aimbot_fov = "FOV del Aimbot", aimbot_smooth = "Suavidad",
        aimbot_wallcheck = "Aimbot Verificar Pared", triggerbot = "Triggerbot",
        triggerbot_delay = "Retardo del Triggerbot", head_expander = "Expansor de Cabeza",
        head_size = "Tamano de Cabeza", backstab = "Apunalar por Detras",
        no_recoil = "Sin Retroceso", no_spread = "Sin Dispersion", rapid_fire = "Disparo Rapido",
        fast_reload = "Recarga Rapida", insta_reload = "Recarga Instantanea",
        infinite_ammo = "Municion Infinita", auto_shoot = "Disparo Automatico",
        auto_shoot_fov = "FOV Disparo Auto",
        speed = "Velocidad", speed_value = "Valor Velocidad", air_jump = "Salto en el Aire",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Distancia Maxima", weapon_esp = "ESP de Arma",
        armor_esp = "ESP de Armadura", grenade_esp = "ESP de Granada",
        damage_indicator = "Indicador de Dano",
        low_graphics = "Graficos Bajos", no_shadows = "Sin Sombras",
        no_fog = "Sin Niebla", no_particles = "Sin Particulas",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-Votekick",
        interface_label = "Interfaz", save_config = "Guardar Config", load_config = "Cargar Config",
        info_label = "Info", key_minimize = "K = Minimizar UI",
        keybind_help1 = "Cada funcion tiene su tecla", keybind_help2 = "Click para grabar",
        unload_script = "Descargar Script", version_text = "Infinite Zen v1.0",
        on = "Encendido", off = "Apagado", key = "tecla",
        config_saved = "Config guardada", config_loaded = "Config cargada",
        config_error_save = "Error al guardar", config_error_load = "Sin config",
        config_error_corrupt = "Archivo corrupto", keybind_locked = "Tecla Bloqueada",
        keybind_locked_desc = "K reservada para UI", keybind_inuse = "En Uso",
        keybind_inuse_desc = " ya usada por: ", backstab_target = "Backstab: ",
        no_enemy = "Sin enemigos", config_title = "Config", error_title = "Error",
        load_title = "Cargar", unsupported_title = "Juego No Soportado",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- FRANÇAIS
    -- ═══════════════════════════════════════════════════════════
    ["fr"] = {
        flag = "FR", displayName = "Francais (FR)", shortCode = "FR",
        hub_name = "INFINITE ZEN", hub_subtitle = "Edition Arsenal", language_label = "Langue",
        tab_combat = "Combat", tab_weapon = "Armes", tab_movement = "Mouvement",
        tab_visuals = "Visuels", tab_settings = "Reglages", tab_credits = "Credits",
        silent_headshot = "Headshot Silencieux", silent_fov = "FOV Silencieux",
        aimbot = "Aimbot", aimbot_fov = "FOV Aimbot", aimbot_smooth = "Douceur",
        aimbot_wallcheck = "Aimbot Verif Mur", triggerbot = "Triggerbot",
        triggerbot_delay = "Delai Triggerbot", head_expander = "Expansion Tete",
        head_size = "Taille Tete", backstab = "Poignarder",
        no_recoil = "Sans Recul", no_spread = "Sans Dispersion", rapid_fire = "Tir Rapide",
        fast_reload = "Recharge Rapide", insta_reload = "Recharge Instant",
        infinite_ammo = "Munitions Infinies", auto_shoot = "Tir Auto",
        auto_shoot_fov = "FOV Tir Auto",
        speed = "Vitesse", speed_value = "Valeur Vitesse", air_jump = "Saut Aerien",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Distance Max", weapon_esp = "ESP Arme",
        armor_esp = "ESP Armure", grenade_esp = "ESP Grenade",
        damage_indicator = "Indicateur Degats",
        low_graphics = "Bas Graphismes", no_shadows = "Sans Ombres",
        no_fog = "Sans Brouillard", no_particles = "Sans Particules",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Interface", save_config = "Sauver Config", load_config = "Charger Config",
        info_label = "Info", key_minimize = "K = Minimiser UI",
        keybind_help1 = "Chaque fonction a sa touche", keybind_help2 = "Cliquer pour enregistrer",
        unload_script = "Decharger Script", version_text = "Infinite Zen v1.0",
        on = "ACTIF", off = "INACTIF", key = "touche",
        config_saved = "Config sauvee", config_loaded = "Config chargee",
        config_error_save = "Erreur sauvegarde", config_error_load = "Aucun config",
        config_error_corrupt = "Fichier corrompu", keybind_locked = "Touche Bloquee",
        keybind_locked_desc = "K reservee pour UI", keybind_inuse = "En Utilisation",
        keybind_inuse_desc = " deja utilisee par: ", backstab_target = "Backstab: ",
        no_enemy = "Aucun ennemi", config_title = "Config", error_title = "Erreur",
        load_title = "Charger", unsupported_title = "Jeu Non Supporte",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- DEUTSCH
    -- ═══════════════════════════════════════════════════════════
    ["de"] = {
        flag = "DE", displayName = "Deutsch (DE)", shortCode = "DE",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Edition", language_label = "Sprache",
        tab_combat = "Kampf", tab_weapon = "Waffen", tab_movement = "Bewegung",
        tab_visuals = "Visuell", tab_settings = "Einstellungen", tab_credits = "Credits",
        silent_headshot = "Stiller Kopfschuss", silent_fov = "Silent FOV",
        aimbot = "Aimbot", aimbot_fov = "Aimbot FOV", aimbot_smooth = "Glatte",
        aimbot_wallcheck = "Aimbot Wandcheck", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Verzogerung", head_expander = "Kopf Expander",
        head_size = "Kopfgrosse", backstab = "Ruckenstich",
        no_recoil = "Kein Ruckstoss", no_spread = "Keine Streuung", rapid_fire = "Schnellfeuer",
        fast_reload = "Schnelles Nachladen", insta_reload = "Sofort Nachladen",
        infinite_ammo = "Unendlich Munition", auto_shoot = "Auto Schiessen",
        auto_shoot_fov = "Auto Schiessen FOV",
        speed = "Geschwindigkeit", speed_value = "Geschwindigkeit Wert", air_jump = "Luftsprung",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Max Entfernung", weapon_esp = "Waffen ESP",
        armor_esp = "Rustung ESP", grenade_esp = "Granate ESP",
        damage_indicator = "Schaden Anzeige",
        low_graphics = "Niedrige Grafik", no_shadows = "Keine Schatten",
        no_fog = "Kein Nebel", no_particles = "Keine Partikel",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Benutzeroberflache", save_config = "Config Speichern",
        load_config = "Config Laden",
        info_label = "Info", key_minimize = "K = UI Minimieren",
        keybind_help1 = "Jede Funktion hat Taste", keybind_help2 = "Klick zum Aufnehmen",
        unload_script = "Script Entladen", version_text = "Infinite Zen v1.0",
        on = "AN", off = "AUS", key = "taste",
        config_saved = "Config gespeichert", config_loaded = "Config geladen",
        config_error_save = "Speichern fehlgeschlagen", config_error_load = "Keine Config",
        config_error_corrupt = "Datei beschadigt", keybind_locked = "Taste Blockiert",
        keybind_locked_desc = "K fur UI reserviert", keybind_inuse = "In Benutzung",
        keybind_inuse_desc = " bereits verwendet von: ", backstab_target = "Backstab: ",
        no_enemy = "Kein Feind", config_title = "Config", error_title = "Fehler",
        load_title = "Laden", unsupported_title = "Spiel Nicht Unterstutzt",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- ITALIANO
    -- ═══════════════════════════════════════════════════════════
    ["it"] = {
        flag = "IT", displayName = "Italiano (IT)", shortCode = "IT",
        hub_name = "INFINITE ZEN", hub_subtitle = "Edizione Arsenal", language_label = "Lingua",
        tab_combat = "Combattimento", tab_weapon = "Armi", tab_movement = "Movimento",
        tab_visuals = "Visuali", tab_settings = "Impostazioni", tab_credits = "Crediti",
        silent_headshot = "Colpo Silenzioso", silent_fov = "FOV Silenzioso",
        aimbot = "Aimbot", aimbot_fov = "FOV Aimbot", aimbot_smooth = "Levigatezza",
        aimbot_wallcheck = "Aimbot Controllo Muri", triggerbot = "Triggerbot",
        triggerbot_delay = "Ritardo Triggerbot", head_expander = "Espansione Testa",
        head_size = "Dimensione Testa", backstab = "Pugnalata",
        no_recoil = "Senza Rinculo", no_spread = "Senza Dispersione", rapid_fire = "Fuoco Rapido",
        fast_reload = "Ricarica Rapida", insta_reload = "Ricarica Istantanea",
        infinite_ammo = "Munizioni Infinite", auto_shoot = "Fuoco Automatico",
        auto_shoot_fov = "FOV Fuoco Auto",
        speed = "Velocita", speed_value = "Valore Velocita", air_jump = "Salto Aereo",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Distanza Max", weapon_esp = "ESP Arma",
        armor_esp = "ESP Armatura", grenade_esp = "ESP Granata",
        damage_indicator = "Indicatore Danni",
        low_graphics = "Grafica Bassa", no_shadows = "Senza Ombre",
        no_fog = "Senza Nebbia", no_particles = "Senza Particelle",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Interfaccia", save_config = "Salva Config",
        load_config = "Carica Config",
        info_label = "Info", key_minimize = "K = Minimizza UI",
        keybind_help1 = "Ogni funzione ha il tasto", keybind_help2 = "Clicca per registrare",
        unload_script = "Scarica Script", version_text = "Infinite Zen v1.0",
        on = "ON", off = "OFF", key = "tasto",
        config_saved = "Config salvata", config_loaded = "Config caricata",
        config_error_save = "Salvataggio fallito", config_error_load = "Nessuna config",
        config_error_corrupt = "File corrotto", keybind_locked = "Tasto Bloccato",
        keybind_locked_desc = "K riservato UI", keybind_inuse = "In Uso",
        keybind_inuse_desc = " gia usato da: ", backstab_target = "Backstab: ",
        no_enemy = "Nessun nemico", config_title = "Config", error_title = "Errore",
        load_title = "Carica", unsupported_title = "Gioco Non Supportato",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- РУССКИЙ (RUSSIAN)
    -- ═══════════════════════════════════════════════════════════
    ["ru"] = {
        flag = "RU", displayName = "Russkiy (RU)", shortCode = "RU",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Ediciya", language_label = "Yazyk",
        tab_combat = "Boy", tab_weapon = "Orujie", tab_movement = "Dvijenie",
        tab_visuals = "Vizual", tab_settings = "Nastroyki", tab_credits = "Titry",
        silent_headshot = "Tihiy Headshot", silent_fov = "Tihiy FOV",
        aimbot = "Aimbot", aimbot_fov = "FOV Aimbot", aimbot_smooth = "Plavnost",
        aimbot_wallcheck = "Aimbot Proverka Sten", triggerbot = "Triggerbot",
        triggerbot_delay = "Zaderjka Triggerbot", head_expander = "Rasshirenie Golovy",
        head_size = "Razmer Golovy", backstab = "Udar v Spinu",
        no_recoil = "Bez Otda4i", no_spread = "Bez Razbrosa", rapid_fire = "Bystry Ogon",
        fast_reload = "Bystraya Perezar", insta_reload = "Mgnovenno Perezar",
        infinite_ammo = "Beskonechnye Patrony", auto_shoot = "Avto Ogon",
        auto_shoot_fov = "FOV Avto Ognya",
        speed = "Skorost", speed_value = "Znachenie Skorosti", air_jump = "Pryjok v Vozduhe",
        auto_bhop = "Avto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Maks. Distanciya", weapon_esp = "ESP Orujiya",
        armor_esp = "ESP Broni", grenade_esp = "ESP Granaty",
        damage_indicator = "Indikator Urona",
        low_graphics = "Nizkaya Grafika", no_shadows = "Bez Teney",
        no_fog = "Bez Tumana", no_particles = "Bez Chastic",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Interfeys", save_config = "Sohranit Config",
        load_config = "Zagruzit Config",
        info_label = "Info", key_minimize = "K = Svernut UI",
        keybind_help1 = "Kajdaya funkciya imeet klavishu", keybind_help2 = "Najat dlya zapisi",
        unload_script = "Vygruzit Script", version_text = "Infinite Zen v1.0",
        on = "VKL", off = "VYKL", key = "klavisha",
        config_saved = "Config sohranen", config_loaded = "Config zagrujen",
        config_error_save = "Oshibka sohraneniya", config_error_load = "Net config",
        config_error_corrupt = "Fayl povrejdyon", keybind_locked = "Klavisha Zablokirovana",
        keybind_locked_desc = "K dlya UI", keybind_inuse = "Ispolzuetsya",
        keybind_inuse_desc = " uje ispolzuetsya: ", backstab_target = "Backstab: ",
        no_enemy = "Net vraga", config_title = "Config", error_title = "Oshibka",
        load_title = "Zagruzit", unsupported_title = "Igra Ne Podderjivaetsya",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- POLSKI
    -- ═══════════════════════════════════════════════════════════
    ["pl"] = {
        flag = "PL", displayName = "Polski (PL)", shortCode = "PL",
        hub_name = "INFINITE ZEN", hub_subtitle = "Edycja Arsenal", language_label = "Jezyk",
        tab_combat = "Walka", tab_weapon = "Bronie", tab_movement = "Ruch",
        tab_visuals = "Wizualia", tab_settings = "Ustawienia", tab_credits = "Autorzy",
        silent_headshot = "Cichy Headshot", silent_fov = "Cichy FOV",
        aimbot = "Aimbot", aimbot_fov = "FOV Aimbot", aimbot_smooth = "Gladkosc",
        aimbot_wallcheck = "Aimbot Sprawdz Sciany", triggerbot = "Triggerbot",
        triggerbot_delay = "Opuznienie Triggerbot", head_expander = "Rozszerzenie Glowy",
        head_size = "Rozmiar Glowy", backstab = "Cios w Plecy",
        no_recoil = "Bez Odrzutu", no_spread = "Bez Rozrzutu", rapid_fire = "Szybki Ogon",
        fast_reload = "Szybkie Przeladowanie", insta_reload = "Natychmiast Przeladuj",
        infinite_ammo = "Nieskonczona Amunicja", auto_shoot = "Auto Strzal",
        auto_shoot_fov = "FOV Auto Strzalu",
        speed = "Predkosc", speed_value = "Wartosc Predkosci", air_jump = "Skok w Powietrzu",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Maks Odleglosc", weapon_esp = "ESP Broni",
        armor_esp = "ESP Zbroi", grenade_esp = "ESP Granatu",
        damage_indicator = "Wskaznik Obrazen",
        low_graphics = "Niska Grafika", no_shadows = "Bez Cieni",
        no_fog = "Bez Mgly", no_particles = "Bez Czesci",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Interfejs", save_config = "Zapisz Config",
        load_config = "Wczytaj Config",
        info_label = "Info", key_minimize = "K = Minimalizuj UI",
        keybind_help1 = "Kazda funkcja ma klawisz", keybind_help2 = "Kliknij aby nagrac",
        unload_script = "Wyladuj Script", version_text = "Infinite Zen v1.0",
        on = "WL", off = "WYL", key = "klawisz",
        config_saved = "Config zapisany", config_loaded = "Config wczytany",
        config_error_save = "Blad zapisu", config_error_load = "Brak config",
        config_error_corrupt = "Plik uszkodzony", keybind_locked = "Klawisz Zablokowany",
        keybind_locked_desc = "K dla UI", keybind_inuse = "Uzywany",
        keybind_inuse_desc = " juz uzywany przez: ", backstab_target = "Backstab: ",
        no_enemy = "Brak wroga", config_title = "Config", error_title = "Blad",
        load_title = "Wczytaj", unsupported_title = "Gra Nieobslugiwana",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- TÜRKÇE
    -- ═══════════════════════════════════════════════════════════
    ["tr"] = {
        flag = "TR", displayName = "Turkce (TR)", shortCode = "TR",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Surumu", language_label = "Dil",
        tab_combat = "Savas", tab_weapon = "Silahlar", tab_movement = "Hareket",
        tab_visuals = "Gorsel", tab_settings = "Ayarlar", tab_credits = "Krediler",
        silent_headshot = "Sessiz Headshot", silent_fov = "Sessiz FOV",
        aimbot = "Aimbot", aimbot_fov = "Aimbot FOV", aimbot_smooth = "Yumusaklik",
        aimbot_wallcheck = "Aimbot Duvar Kontrol", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Gecikme", head_expander = "Kafa Buyutucu",
        head_size = "Kafa Boyutu", backstab = "Sirtindan Bicak",
        no_recoil = "Geri Tepme Yok", no_spread = "Yayilma Yok", rapid_fire = "Hizli Ates",
        fast_reload = "Hizli Sarjor", insta_reload = "Anlik Sarjor",
        infinite_ammo = "Sinirsiz Mermi", auto_shoot = "Otomatik Ates",
        auto_shoot_fov = "Otomatik Ates FOV",
        speed = "Hiz", speed_value = "Hiz Degeri", air_jump = "Havada Zipla",
        auto_bhop = "Otomatik Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Maks Mesafe", weapon_esp = "Silah ESP",
        armor_esp = "Zirh ESP", grenade_esp = "Bomba ESP",
        damage_indicator = "Hasar Gostergesi",
        low_graphics = "Dusuk Grafik", no_shadows = "Golge Yok",
        no_fog = "Sis Yok", no_particles = "Parcacik Yok",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Arayuz", save_config = "Config Kaydet",
        load_config = "Config Yukle",
        info_label = "Bilgi", key_minimize = "K = UI Kucult",
        keybind_help1 = "Her ozellik kendi tusu", keybind_help2 = "Kaydetmek icin tikla",
        unload_script = "Script Kaldir", version_text = "Infinite Zen v1.0",
        on = "ACIK", off = "KAPALI", key = "tus",
        config_saved = "Config kaydedildi", config_loaded = "Config yuklendi",
        config_error_save = "Kaydetme hatasi", config_error_load = "Config yok",
        config_error_corrupt = "Bozuk dosya", keybind_locked = "Tus Kilitli",
        keybind_locked_desc = "K UI icin ayrildi", keybind_inuse = "Kullanimda",
        keybind_inuse_desc = " zaten kullaniliyor: ", backstab_target = "Backstab: ",
        no_enemy = "Dusman yok", config_title = "Config", error_title = "Hata",
        load_title = "Yukle", unsupported_title = "Oyun Desteklenmiyor",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- INDONESIA
    -- ═══════════════════════════════════════════════════════════
    ["id"] = {
        flag = "ID", displayName = "Bahasa Indonesia (ID)", shortCode = "ID",
        hub_name = "INFINITE ZEN", hub_subtitle = "Edisi Arsenal", language_label = "Bahasa",
        tab_combat = "Tempur", tab_weapon = "Senjata", tab_movement = "Gerakan",
        tab_visuals = "Visual", tab_settings = "Pengaturan", tab_credits = "Kredit",
        silent_headshot = "Headshot Senyap", silent_fov = "FOV Senyap",
        aimbot = "Aimbot", aimbot_fov = "FOV Aimbot", aimbot_smooth = "Kehalusan",
        aimbot_wallcheck = "Aimbot Cek Dinding", triggerbot = "Triggerbot",
        triggerbot_delay = "Delay Triggerbot", head_expander = "Pembesar Kepala",
        head_size = "Ukuran Kepala", backstab = "Tusuk Belakang",
        no_recoil = "Tanpa Recoil", no_spread = "Tanpa Sebar", rapid_fire = "Tembak Cepat",
        fast_reload = "Reload Cepat", insta_reload = "Reload Instan",
        infinite_ammo = "Amunisi Tak Terbatas", auto_shoot = "Tembak Otomatis",
        auto_shoot_fov = "FOV Tembak Auto",
        speed = "Kecepatan", speed_value = "Nilai Kecepatan", air_jump = "Lompat Udara",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Jarak Maks", weapon_esp = "ESP Senjata",
        armor_esp = "ESP Armor", grenade_esp = "ESP Granat",
        damage_indicator = "Indikator Damage",
        low_graphics = "Grafik Rendah", no_shadows = "Tanpa Bayangan",
        no_fog = "Tanpa Kabut", no_particles = "Tanpa Partikel",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Antarmuka", save_config = "Simpan Config",
        load_config = "Muat Config",
        info_label = "Info", key_minimize = "K = Kecilkan UI",
        keybind_help1 = "Setiap fitur punya tombol", keybind_help2 = "Klik untuk rekam",
        unload_script = "Bongkar Script", version_text = "Infinite Zen v1.0",
        on = "AKTIF", off = "MATI", key = "tombol",
        config_saved = "Config disimpan", config_loaded = "Config dimuat",
        config_error_save = "Gagal menyimpan", config_error_load = "Tidak ada config",
        config_error_corrupt = "File rusak", keybind_locked = "Tombol Terkunci",
        keybind_locked_desc = "K untuk UI", keybind_inuse = "Dipakai",
        keybind_inuse_desc = " sudah dipakai oleh: ", backstab_target = "Backstab: ",
        no_enemy = "Tidak ada musuh", config_title = "Config", error_title = "Error",
        load_title = "Muat", unsupported_title = "Game Tidak Didukung",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- FILIPINO
    -- ═══════════════════════════════════════════════════════════
    ["tl"] = {
        flag = "PH", displayName = "Filipino (PH)", shortCode = "PH",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Edition", language_label = "Wika",
        tab_combat = "Laban", tab_weapon = "Sandata", tab_movement = "Galaw",
        tab_visuals = "Biswal", tab_settings = "Settings", tab_credits = "Credits",
        silent_headshot = "Tahimik na Headshot", silent_fov = "Tahimik na FOV",
        aimbot = "Aimbot", aimbot_fov = "FOV Aimbot", aimbot_smooth = "Kininis",
        aimbot_wallcheck = "Aimbot Check Pader", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Delay", head_expander = "Palakihin Ulo",
        head_size = "Laki ng Ulo", backstab = "Saksak sa Likod",
        no_recoil = "Walang Recoil", no_spread = "Walang Spread", rapid_fire = "Mabilis na Putok",
        fast_reload = "Mabilis Reload", insta_reload = "Instant Reload",
        infinite_ammo = "Walang Hanggang Bala", auto_shoot = "Auto Putok",
        auto_shoot_fov = "FOV Auto Putok",
        speed = "Bilis", speed_value = "Halaga ng Bilis", air_jump = "Talon sa Hangin",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Max Distansya", weapon_esp = "ESP Sandata",
        armor_esp = "ESP Armor", grenade_esp = "ESP Granade",
        damage_indicator = "Indicator ng Damage",
        low_graphics = "Mababang Graphics", no_shadows = "Walang Anino",
        no_fog = "Walang Fog", no_particles = "Walang Particles",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Interface", save_config = "I-save Config",
        load_config = "I-load Config",
        info_label = "Info", key_minimize = "K = I-minimize UI",
        keybind_help1 = "Bawat feature may key", keybind_help2 = "I-click para mag-record",
        unload_script = "I-unload Script", version_text = "Infinite Zen v1.0",
        on = "ON", off = "OFF", key = "key",
        config_saved = "Na-save ang Config", config_loaded = "Na-load ang Config",
        config_error_save = "Bigong i-save", config_error_load = "Walang config",
        config_error_corrupt = "Sira ang file", keybind_locked = "Naka-lock na Key",
        keybind_locked_desc = "K para sa UI", keybind_inuse = "Ginagamit",
        keybind_inuse_desc = " ginagamit na ng: ", backstab_target = "Backstab: ",
        no_enemy = "Walang kalaban", config_title = "Config", error_title = "Error",
        load_title = "I-load", unsupported_title = "Hindi Suportadong Laro",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- TIẾNG VIỆT
    -- ═══════════════════════════════════════════════════════════
    ["vi"] = {
        flag = "VN", displayName = "Tieng Viet (VN)", shortCode = "VN",
        hub_name = "INFINITE ZEN", hub_subtitle = "Phien Ban Arsenal", language_label = "Ngon ngu",
        tab_combat = "Chien dau", tab_weapon = "Vu khi", tab_movement = "Di chuyen",
        tab_visuals = "Hinh anh", tab_settings = "Cai dat", tab_credits = "Ghi cong",
        silent_headshot = "Headshot Im Lang", silent_fov = "FOV Im Lang",
        aimbot = "Aimbot", aimbot_fov = "FOV Aimbot", aimbot_smooth = "Do Muot",
        aimbot_wallcheck = "Aimbot Kiem Tra Tuong", triggerbot = "Triggerbot",
        triggerbot_delay = "Do Tre Triggerbot", head_expander = "Mo Rong Dau",
        head_size = "Kich Thuoc Dau", backstab = "Dau Sau Lung",
        no_recoil = "Khong Giat", no_spread = "Khong Lan", rapid_fire = "Ban Nhanh",
        fast_reload = "Nap Nhanh", insta_reload = "Nap Ngay",
        infinite_ammo = "Dan Vo Han", auto_shoot = "Ban Tu Dong",
        auto_shoot_fov = "FOV Ban Tu Dong",
        speed = "Toc do", speed_value = "Gia tri Toc do", air_jump = "Nhay Tren Khong",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Khoang Cach Max", weapon_esp = "ESP Vu Khi",
        armor_esp = "ESP Giap", grenade_esp = "ESP Luu Dan",
        damage_indicator = "Chi Bao Sat Thuong",
        low_graphics = "Do Hoa Thap", no_shadows = "Khong Bong",
        no_fog = "Khong Suong Mu", no_particles = "Khong Hat",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Giao Dien", save_config = "Luu Config",
        load_config = "Tai Config",
        info_label = "Thong Tin", key_minimize = "K = Thu Nho UI",
        keybind_help1 = "Moi tinh nang co phim rieng", keybind_help2 = "Nhan de ghi",
        unload_script = "Go Script", version_text = "Infinite Zen v1.0",
        on = "BAT", off = "TAT", key = "phim",
        config_saved = "Da luu Config", config_loaded = "Da tai Config",
        config_error_save = "Luu that bai", config_error_load = "Khong co Config",
        config_error_corrupt = "File hong", keybind_locked = "Phim Bi Khoa",
        keybind_locked_desc = "K danh cho UI", keybind_inuse = "Dang Dung",
        keybind_inuse_desc = " da duoc dung boi: ", backstab_target = "Backstab: ",
        no_enemy = "Khong co dich", config_title = "Config", error_title = "Loi",
        load_title = "Tai", unsupported_title = "Game Khong Ho Tro",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- 日本語 (JAPANESE)
    -- ═══════════════════════════════════════════════════════════
    ["ja"] = {
        flag = "JP", displayName = "Nihongo (JP)", shortCode = "JP",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Ban", language_label = "Gengo",
        tab_combat = "Sentou", tab_weapon = "Buki", tab_movement = "Idou",
        tab_visuals = "Bijuaru", tab_settings = "Settei", tab_credits = "Kurejitto",
        silent_headshot = "Silent Headshot", silent_fov = "Silent FOV",
        aimbot = "Aimbot", aimbot_fov = "Aimbot FOV", aimbot_smooth = "Nameraka",
        aimbot_wallcheck = "Aimbot Kabe Check", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Delay", head_expander = "Atama Kakudai",
        head_size = "Atama Saizu", backstab = "Haigo Sasu",
        no_recoil = "Recoil Nashi", no_spread = "Spread Nashi", rapid_fire = "Renzoku",
        fast_reload = "Hayai Reload", insta_reload = "Sokuji Reload",
        infinite_ammo = "Mugen Dan", auto_shoot = "Jidou Shageki",
        auto_shoot_fov = "Jidou Shageki FOV",
        speed = "Sokudo", speed_value = "Sokudo Atai", air_jump = "Kuuchuu Jump",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Max Kyori", weapon_esp = "Buki ESP",
        armor_esp = "Yoroi ESP", grenade_esp = "Grenade ESP",
        damage_indicator = "Damage Indicator",
        low_graphics = "Tei Graphics", no_shadows = "Kage Nashi",
        no_fog = "Kiri Nashi", no_particles = "Particle Nashi",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "UI", save_config = "Config Hozon",
        load_config = "Config Yomikomi",
        info_label = "Jouhou", key_minimize = "K = UI Shoushou",
        keybind_help1 = "Kaku Kinou ni Key", keybind_help2 = "Click de Kiroku",
        unload_script = "Script Unload", version_text = "Infinite Zen v1.0",
        on = "ON", off = "OFF", key = "key",
        config_saved = "Config Hozon", config_loaded = "Config Yomikomi",
        config_error_save = "Hozon Shippai", config_error_load = "Config Nashi",
        config_error_corrupt = "File Koware", keybind_locked = "Key Lock",
        keybind_locked_desc = "K wa UI ni Shiyou", keybind_inuse = "Shiyou Chuu",
        keybind_inuse_desc = " sudeni shiyou: ", backstab_target = "Backstab: ",
        no_enemy = "Teki Nashi", config_title = "Config", error_title = "Error",
        load_title = "Yomikomi", unsupported_title = "Mitaigame",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- 한국어 (KOREAN)
    -- ═══════════════════════════════════════════════════════════
    ["ko"] = {
        flag = "KR", displayName = "Hangugeo (KR)", shortCode = "KR",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Paen", language_label = "Eoneo",
        tab_combat = "Jeontu", tab_weapon = "Mugi", tab_movement = "Idong",
        tab_visuals = "Sigak", tab_settings = "Seoljeong", tab_credits = "Kuredit",
        silent_headshot = "Silent Headshot", silent_fov = "Silent FOV",
        aimbot = "Aimbot", aimbot_fov = "Aimbot FOV", aimbot_smooth = "Bumae",
        aimbot_wallcheck = "Aimbot Byeok Check", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Jiyon", head_expander = "Meori Hwakdae",
        head_size = "Meori Keugi", backstab = "Dwitjjireugi",
        no_recoil = "Bandong Eopseum", no_spread = "Hwasan Eopseum", rapid_fire = "Ppaso",
        fast_reload = "Ppareun Reload", insta_reload = "Jeukseok Reload",
        infinite_ammo = "Muhan Chongal", auto_shoot = "Jadong Sagyeok",
        auto_shoot_fov = "Jadong Sagyeok FOV",
        speed = "Sokdo", speed_value = "Sokdo Gaps", air_jump = "Gongjung Jeompeu",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Chwedae Geori", weapon_esp = "Mugi ESP",
        armor_esp = "Bangho ESP", grenade_esp = "Suryu ESP",
        damage_indicator = "Damage Pyosi",
        low_graphics = "Najeun Graphics", no_shadows = "Geurimja Eopseum",
        no_fog = "Angae Eopseum", no_particles = "Ipja Eopseum",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "UI", save_config = "Config Jeojang",
        load_config = "Config Bulleo",
        info_label = "Jeongbo", key_minimize = "K = UI Chuso",
        keybind_help1 = "Gak Gineung Kireul", keybind_help2 = "Clickhayeo Girok",
        unload_script = "Script Eonro", version_text = "Infinite Zen v1.0",
        on = "ON", off = "OFF", key = "ki",
        config_saved = "Config Jeojang", config_loaded = "Config Bulleo",
        config_error_save = "Jeojang Silpae", config_error_load = "Config Eopseum",
        config_error_corrupt = "Pail Son", keybind_locked = "Ki Jamgim",
        keybind_locked_desc = "K UI Yeyak", keybind_inuse = "Sayong Jung",
        keybind_inuse_desc = " imi sayong jung: ", backstab_target = "Backstab: ",
        no_enemy = "Jeok Eopseum", config_title = "Config", error_title = "Oryu",
        load_title = "Bulleo", unsupported_title = "Jiwon An Doeneun Game",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- 中文 (CHINESE)
    -- ═══════════════════════════════════════════════════════════
    ["zh-cn"] = {
        flag = "CN", displayName = "Zhongwen (CN)", shortCode = "CN",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Banben", language_label = "Yuyan",
        tab_combat = "Zhandou", tab_weapon = "Wuqi", tab_movement = "Yidong",
        tab_visuals = "Shijue", tab_settings = "Shezhi", tab_credits = "Zhiyuan",
        silent_headshot = "Silent Headshot", silent_fov = "Silent FOV",
        aimbot = "Zimiao", aimbot_fov = "Zimiao FOV", aimbot_smooth = "Pinghua",
        aimbot_wallcheck = "Zimiao Qiang Check", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Yanshi", head_expander = "Toubu Kuoda",
        head_size = "Toubu Daxiao", backstab = "Bei Ci",
        no_recoil = "Wu Houzuo", no_spread = "Wu Kuosan", rapid_fire = "Kuai Su Sheji",
        fast_reload = "Kuai Su Huan Dan", insta_reload = "Shun Jian Huan Dan",
        infinite_ammo = "Wu Xian Zidan", auto_shoot = "Zidong Sheji",
        auto_shoot_fov = "Zidong Sheji FOV",
        speed = "Sudu", speed_value = "Sudu Zhi", air_jump = "Kongzhong Tiao",
        auto_bhop = "Zidong Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Zuida Juli", weapon_esp = "Wuqi ESP",
        armor_esp = "Hujia ESP", grenade_esp = "Shoulei ESP",
        damage_indicator = "Shanghai Zhishi",
        low_graphics = "Di Huazhi", no_shadows = "Wu Yingzi",
        no_fog = "Wu Wu", no_particles = "Wu Lizi",
        anti_flash = "Fang Shanguang", anti_votekick = "Fang Tou Piao",
        interface_label = "Jiemian", save_config = "Baocun Peizhi",
        load_config = "Jiazai Peizhi",
        info_label = "Xinxi", key_minimize = "K = Zuixiao UI",
        keybind_help1 = "Mei Gongneng You Jian", keybind_help2 = "Dianji Luxiang",
        unload_script = "Xiezai Script", version_text = "Infinite Zen v1.0",
        on = "Kai", off = "Guan", key = "jian",
        config_saved = "Peizhi Yibaocun", config_loaded = "Peizhi Yijiazai",
        config_error_save = "Baocun Shibai", config_error_load = "Wu Peizhi",
        config_error_corrupt = "Wenjian Sunhuai", keybind_locked = "Jian Suoding",
        keybind_locked_desc = "K Yuyue UI", keybind_inuse = "Shiyong Zhong",
        keybind_inuse_desc = " Yi Bei Shiyong: ", backstab_target = "Backstab: ",
        no_enemy = "Wu Diren", config_title = "Peizhi", error_title = "Cuowu",
        load_title = "Jiazai", unsupported_title = "Bu Zhichi De Youxi",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- العربية (ARABIC)
    -- ═══════════════════════════════════════════════════════════
    ["ar"] = {
        flag = "SA", displayName = "Al Arabiya (SA)", shortCode = "SA",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Edition", language_label = "Lugha",
        tab_combat = "Qital", tab_weapon = "Asliha", tab_movement = "Haraka",
        tab_visuals = "Basari", tab_settings = "Iidadat", tab_credits = "Shukr",
        silent_headshot = "Headshot Samit", silent_fov = "FOV Samit",
        aimbot = "Aimbot", aimbot_fov = "FOV Aimbot", aimbot_smooth = "Naim",
        aimbot_wallcheck = "Aimbot Jidar", triggerbot = "Triggerbot",
        triggerbot_delay = "Takheer Triggerbot", head_expander = "Tawsee Ras",
        head_size = "Hajm Ras", backstab = "Taen Khalfi",
        no_recoil = "Bidun Irtidad", no_spread = "Bidun Intishar", rapid_fire = "Ramie Sari",
        fast_reload = "Taelia Saria", insta_reload = "Taelia Fawria",
        infinite_ammo = "Thakheera La Nihaia", auto_shoot = "Ramie Tilaqai",
        auto_shoot_fov = "FOV Ramie Auto",
        speed = "Sura", speed_value = "Qimat Sura", air_jump = "Qafz Jawa",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Aqsa Masaafa", weapon_esp = "ESP Silah",
        armor_esp = "ESP Dira", grenade_esp = "ESP Qunbula",
        damage_indicator = "Muashir Dharar",
        low_graphics = "Rusumat Munakhfida", no_shadows = "Bidun Dilal",
        no_fog = "Bidun Dabab", no_particles = "Bidun Juziat",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Wajha", save_config = "Hifz Config",
        load_config = "Tahmil Config",
        info_label = "Maalumat", key_minimize = "K = Tasghir UI",
        keybind_help1 = "Kul Miza Sirr", keybind_help2 = "Idghat Lil Tasjil",
        unload_script = "Ikhraj Script", version_text = "Infinite Zen v1.0",
        on = "Tashghil", off = "Itfa", key = "sirr",
        config_saved = "Hufiz Config", config_loaded = "Humil Config",
        config_error_save = "Fashal Hifz", config_error_load = "La Config",
        config_error_corrupt = "Milaf Talif", keybind_locked = "Sirr Muqfal",
        keybind_locked_desc = "K L UI", keybind_inuse = "Mustakhdim",
        keybind_inuse_desc = " Mustakhdim Min: ", backstab_target = "Backstab: ",
        no_enemy = "La Adu", config_title = "Config", error_title = "Khata",
        load_title = "Tahmil", unsupported_title = "Liaba Ghair Madum",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- हिन्दी (HINDI)
    -- ═══════════════════════════════════════════════════════════
    ["hi"] = {
        flag = "IN", displayName = "Hindi (IN)", shortCode = "IN",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Sanskaran", language_label = "Bhasha",
        tab_combat = "Yuddh", tab_weapon = "Hathiyar", tab_movement = "Gati",
        tab_visuals = "Drishya", tab_settings = "Settings", tab_credits = "Shrey",
        silent_headshot = "Silent Headshot", silent_fov = "Silent FOV",
        aimbot = "Aimbot", aimbot_fov = "Aimbot FOV", aimbot_smooth = "Komalta",
        aimbot_wallcheck = "Aimbot Deewar Check", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Deri", head_expander = "Sir Vistar",
        head_size = "Sir Aakar", backstab = "Peechhe Vaar",
        no_recoil = "Bina Recoil", no_spread = "Bina Failav", rapid_fire = "Tewr Goli",
        fast_reload = "Tewr Reload", insta_reload = "Turant Reload",
        infinite_ammo = "Anant Goliyaan", auto_shoot = "Auto Goli",
        auto_shoot_fov = "Auto Goli FOV",
        speed = "Gati", speed_value = "Gati Maan", air_jump = "Hawa Mein Kood",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Adhiktam Doori", weapon_esp = "Hathiyar ESP",
        armor_esp = "Kavach ESP", grenade_esp = "Grenade ESP",
        damage_indicator = "Nuksan Suchak",
        low_graphics = "Kam Graphics", no_shadows = "Bina Chhaya",
        no_fog = "Bina Dhundh", no_particles = "Bina Kank",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Interface", save_config = "Config Savesh",
        load_config = "Config Load",
        info_label = "Jankari", key_minimize = "K = UI Chhota",
        keybind_help1 = "Har Feature Ki Apni Key", keybind_help2 = "Record Ke Liye Click",
        unload_script = "Script Unload", version_text = "Infinite Zen v1.0",
        on = "ON", off = "OFF", key = "key",
        config_saved = "Config Savesh", config_loaded = "Config Load",
        config_error_save = "Savesh Fail", config_error_load = "Koi Config Nahin",
        config_error_corrupt = "File Kharaab", keybind_locked = "Key Lock",
        keybind_locked_desc = "K UI Ke Liye", keybind_inuse = "Prayog Mein",
        keybind_inuse_desc = " Pehle Se Prayog: ", backstab_target = "Backstab: ",
        no_enemy = "Koi Dushman Nahin", config_title = "Config", error_title = "Error",
        load_title = "Load", unsupported_title = "Game Support Nahin",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- NEDERLANDS
    -- ═══════════════════════════════════════════════════════════
    ["nl"] = {
        flag = "NL", displayName = "Nederlands (NL)", shortCode = "NL",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Editie", language_label = "Taal",
        tab_combat = "Gevecht", tab_weapon = "Wapens", tab_movement = "Beweging",
        tab_visuals = "Visueel", tab_settings = "Instellingen", tab_credits = "Credits",
        silent_headshot = "Stille Headshot", silent_fov = "Stille FOV",
        aimbot = "Aimbot", aimbot_fov = "Aimbot FOV", aimbot_smooth = "Vloeiend",
        aimbot_wallcheck = "Aimbot Muur Check", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Vertraging", head_expander = "Hoofd Vergroten",
        head_size = "Hoofd Grootte", backstab = "Rug Steek",
        no_recoil = "Geen Terugslag", no_spread = "Geen Verspreiding", rapid_fire = "Snel Vuren",
        fast_reload = "Snel Herladen", insta_reload = "Direct Herladen",
        infinite_ammo = "Oneindige Munitie", auto_shoot = "Auto Schieten",
        auto_shoot_fov = "Auto Schiet FOV",
        speed = "Snelheid", speed_value = "Snelheid Waarde", air_jump = "Lucht Sprong",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Max Afstand", weapon_esp = "Wapen ESP",
        armor_esp = "Pantser ESP", grenade_esp = "Granaat ESP",
        damage_indicator = "Schade Indicator",
        low_graphics = "Lage Graphics", no_shadows = "Geen Schaduwen",
        no_fog = "Geen Mist", no_particles = "Geen Deeltjes",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Interface", save_config = "Config Opslaan",
        load_config = "Config Laden",
        info_label = "Info", key_minimize = "K = UI Minimaliseren",
        keybind_help1 = "Elke Functie Heeft Key", keybind_help2 = "Klik Om Op Te Nemen",
        unload_script = "Script Ontladen", version_text = "Infinite Zen v1.0",
        on = "AAN", off = "UIT", key = "toets",
        config_saved = "Config Opgeslagen", config_loaded = "Config Geladen",
        config_error_save = "Opslaan Mislukt", config_error_load = "Geen Config",
        config_error_corrupt = "Bestand Beschadigd", keybind_locked = "Toets Vergrendeld",
        keybind_locked_desc = "K Voor UI", keybind_inuse = "In Gebruik",
        keybind_inuse_desc = " Al In Gebruik Door: ", backstab_target = "Backstab: ",
        no_enemy = "Geen Vijand", config_title = "Config", error_title = "Fout",
        load_title = "Laden", unsupported_title = "Spel Niet Ondersteund",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- SVENSKA
    -- ═══════════════════════════════════════════════════════════
    ["sv"] = {
        flag = "SE", displayName = "Svenska (SE)", shortCode = "SE",
        hub_name = "INFINITE ZEN", hub_subtitle = "Arsenal Utgava", language_label = "Sprak",
        tab_combat = "Strid", tab_weapon = "Vapen", tab_movement = "Rorelse",
        tab_visuals = "Visuell", tab_settings = "Installningar", tab_credits = "Krediter",
        silent_headshot = "Tyst Headshot", silent_fov = "Tyst FOV",
        aimbot = "Aimbot", aimbot_fov = "Aimbot FOV", aimbot_smooth = "Mjuk",
        aimbot_wallcheck = "Aimbot Vagg Check", triggerbot = "Triggerbot",
        triggerbot_delay = "Triggerbot Forsening", head_expander = "Huvud Forstora",
        head_size = "Huvud Storlek", backstab = "Rygg Stick",
        no_recoil = "Ingen Rekyl", no_spread = "Ingen Spridning", rapid_fire = "Snabb Eld",
        fast_reload = "Snabb Omladdning", insta_reload = "Direkt Omladdning",
        infinite_ammo = "Oandlig Ammunition", auto_shoot = "Auto Skjut",
        auto_shoot_fov = "Auto Skjut FOV",
        speed = "Hastighet", speed_value = "Hastighet Varde", air_jump = "Luft Hopp",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Max Avstand", weapon_esp = "Vapen ESP",
        armor_esp = "Rustning ESP", grenade_esp = "Granat ESP",
        damage_indicator = "Skada Indikator",
        low_graphics = "Lag Grafik", no_shadows = "Inga Skuggor",
        no_fog = "Ingen Dimma", no_particles = "Inga Partiklar",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Grassnitt", save_config = "Spara Config",
        load_config = "Ladda Config",
        info_label = "Info", key_minimize = "K = Minimera UI",
        keybind_help1 = "Varje Funktion Har Key", keybind_help2 = "Klicka For Inspelning",
        unload_script = "Ladda Ur Script", version_text = "Infinite Zen v1.0",
        on = "PA", off = "AV", key = "knapp",
        config_saved = "Config Sparad", config_loaded = "Config Laddad",
        config_error_save = "Spara Misslyckades", config_error_load = "Ingen Config",
        config_error_corrupt = "Fil Skadad", keybind_locked = "Knapp Last",
        keybind_locked_desc = "K For UI", keybind_inuse = "Anvands",
        keybind_inuse_desc = " Redan Anvands Av: ", backstab_target = "Backstab: ",
        no_enemy = "Ingen Fiende", config_title = "Config", error_title = "Fel",
        load_title = "Ladda", unsupported_title = "Spel Inte Stott",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },

    -- ═══════════════════════════════════════════════════════════
    -- ROMÂNĂ
    -- ═══════════════════════════════════════════════════════════
    ["ro"] = {
        flag = "RO", displayName = "Romana (RO)", shortCode = "RO",
        hub_name = "INFINITE ZEN", hub_subtitle = "Editia Arsenal", language_label = "Limba",
        tab_combat = "Lupta", tab_weapon = "Arme", tab_movement = "Miscare",
        tab_visuals = "Vizual", tab_settings = "Setari", tab_credits = "Credite",
        silent_headshot = "Headshot Silentios", silent_fov = "FOV Silentios",
        aimbot = "Aimbot", aimbot_fov = "FOV Aimbot", aimbot_smooth = "Netezire",
        aimbot_wallcheck = "Aimbot Verific Perete", triggerbot = "Triggerbot",
        triggerbot_delay = "Intarziere Triggerbot", head_expander = "Extindere Cap",
        head_size = "Marime Cap", backstab = "Junghiere Spate",
        no_recoil = "Fara Recul", no_spread = "Fara Raspandire", rapid_fire = "Foc Rapid",
        fast_reload = "Reincarcare Rapida", insta_reload = "Reincarcare Instant",
        infinite_ammo = "Munitie Infinita", auto_shoot = "Foc Automat",
        auto_shoot_fov = "FOV Foc Auto",
        speed = "Viteza", speed_value = "Valoare Viteza", air_jump = "Saritura Aer",
        auto_bhop = "Auto Bhop", fullbright = "Fullbright",
        esp = "ESP", max_distance = "Distanta Max", weapon_esp = "ESP Arma",
        armor_esp = "ESP Armura", grenade_esp = "ESP Grenada",
        damage_indicator = "Indicator Daune",
        low_graphics = "Grafica Slaba", no_shadows = "Fara Umbre",
        no_fog = "Fara Ceata", no_particles = "Fara Particule",
        anti_flash = "Anti-Flash", anti_votekick = "Anti-VoteKick",
        interface_label = "Interfata", save_config = "Salveaza Config",
        load_config = "Incarca Config",
        info_label = "Info", key_minimize = "K = Minimalizeaza UI",
        keybind_help1 = "Fiecare Functie Are Tasta", keybind_help2 = "Click Pentru Inregistrare",
        unload_script = "Descarca Script", version_text = "Infinite Zen v1.0",
        on = "ON", off = "OFF", key = "tasta",
        config_saved = "Config Salvata", config_loaded = "Config Incarcata",
        config_error_save = "Salvare Esuata", config_error_load = "Fara Config",
        config_error_corrupt = "Fisier Stricat", keybind_locked = "Tasta Blocata",
        keybind_locked_desc = "K Pentru UI", keybind_inuse = "In Folosinta",
        keybind_inuse_desc = " Deja Folosit De: ", backstab_target = "Backstab: ",
        no_enemy = "Fara Dusman", config_title = "Config", error_title = "Eroare",
        load_title = "Incarca", unsupported_title = "Joc Neacceptat",
        unsupported_message_pt = "Este jogo nao e suportado pelo Infinite Zen.",
        unsupported_message_en = "This game is not supported by Infinite Zen.",
    },
}

function Language.get(key)
    local t = Language.translations[Language.current]
    if t and t[key] then return t[key] end
    local fb = Language.translations["en"]
    if fb and fb[key] then return fb[key] end
    return key
end

function Language.setLanguage(code)
    if not Language.translations[code] then
        print("[LANG] Codigo nao encontrado: " .. tostring(code))
        return false
    end
    Language.current = code
    print("[LANG] Idioma alterado para: " .. code)
    if _G.IZ_RefreshLanguage then
        pcall(_G.IZ_RefreshLanguage)
    end
    for _, callback in ipairs(Language.listeners) do
        pcall(callback)
    end
    return true
end

function Language.getCurrent()
    return Language.current
end

function Language.getCurrentData()
    return Language.translations[Language.current]
end

function Language.getAvailable()
    local list = {}
    for code, data in pairs(Language.translations) do
        table.insert(list, {
            code = code,
            flag = data.flag,
            displayName = data.displayName,
            shortCode = data.shortCode,
        })
    end
    table.sort(list, function(a, b) return a.code < b.code end)
    return list
end

function Language.onChange(callback)
    table.insert(Language.listeners, callback)
end

return Language